### PR TITLE
rebase to upstream/main

### PR DESCRIPTION
**Pull request by wllenyj**

### CODE REVIEW

**Comment by sameo** [comment]
This needs to be force pushed. How can we test it before doing so, @stevenhorsman ?

**Comment by stevenhorsman** [comment]
> This needs to be force pushed. How can we test it before doing so, @stevenhorsman ?

I guess the easiest way would be to create a kata-containers branch from CCv0 and update https://github.com/kata-containers/kata-containers/blob/46522a3e46fcb44ce8bb22c35da31f7ff86329fd/versions.yaml#L198 to point to this branch. Then we can create a PR from that and run it through the CCv0 PR CI process. Do you want me to give that a go?

Addition: I guess we would also would need to re-vendor in that branch so that the vendor packages were picked up correctly too?

**Comment by sameo** [comment]
> > This needs to be force pushed. How can we test it before doing so, @stevenhorsman ?
> 
> I guess the easiest way would be to create a kata-containers branch from CCv0 and update https://github.com/kata-containers/kata-containers/blob/46522a3e46fcb44ce8bb22c35da31f7ff86329fd/versions.yaml#L198 to point to this branch. Then we can create a PR from that and run it through the CCv0 PR CI process. Do you want me to give that a go?
> 

That would be fantastic, yes.

> Addition: I guess we would also would need to re-vendor in that branch so that the vendor packages were picked up correctly too?

Indeed. Thanks in advance for your help.

**Comment by stevenhorsman** [comment]
So I'm not saying that this branch hasn't been re-based properly, but I'm getting some strange results in the containerd build.
If we look at the current `ali-CCv0` branch:
```
# git remote -v
origin	https://github.com/confidential-containers/containerd (fetch)
origin	https://github.com/confidential-containers/containerd (push)
# git branch -vv
* ali-CCv0 776bd31b6 [origin/ali-CCv0] [CRI] Fix panic when registry.mirrors use localhost
  main     9c488e5da [origin/main] Merge pull request #6124 from samj1912/large-labels
 # make cri-cni-release
+ bin/ctr
+ bin/containerd
+ bin/containerd-stress
+ bin/containerd-shim
+ bin/containerd-shim-runc-v1
+ bin/containerd-shim-runc-v2
echo "CONTAINERD_VERSION: '1.6.0-beta.0-72-g776bd31b6'" | tee /root/go/src/github.com/confidential-containers/containerd/_output/cri/opt/containerd/cluster/version
CONTAINERD_VERSION: '1.6.0-beta.0-72-g776bd31b6'
 ```
you can see that the binary it produces is version `1.6.0-beta.0-72-g776bd31b6`
Then compare that to this branch:
```
# git remote -v
origin	https://github.com/wllenyj/containerd (fetch)
origin	https://github.com/wllenyj/containerd (push)
# git branch -vv
* CCv0-rebase e5287e3a5 [origin/CCv0-rebase] ctr: Implement the pull-image command
  master      7b7a230dd [origin/master] Merge pull request #5399 from dmcgowan/update-cgroup-vendor
# make cri-cni-release
+ bin/ctr
+ bin/containerd
+ bin/containerd-stress
+ bin/containerd-shim
+ bin/containerd-shim-runc-v1
+ bin/containerd-shim-runc-v2
echo "CONTAINERD_VERSION: '1.2.0-beta.2-6325-ge5287e3a5'" | tee /root/go/src/github.com/wllenyj/containerd/_output/cri/opt/containerd/cluster/version
CONTAINERD_VERSION: '1.2.0-beta.2-6325-ge5287e3a5'
```
you can see that it seems to produce a binary for containerd version `1.2.0-beta.2-6325-ge5287e3a5` which feels wrong!

It might be that something in the `containerd` build process has changed, but we'll need to update our side to compensate. I'll carry on looking into it to see if I can find an explanation.

**Comment by stevenhorsman** [comment]
As another data point I tried the latest `containerd` `main`:
```
# git remote -v
origin	https://github.com/containerd/containerd (fetch)
origin	https://github.com/containerd/containerd (push)
# git branch -vv
* main a9f61ba2c [origin/main] Merge pull request #6524 from dmcgowan/prepare-1.6.0-rc.3
# make cri-cni-release
+ bin/ctr
+ bin/containerd
+ bin/containerd-stress
+ bin/containerd-shim
+ bin/containerd-shim-runc-v1
+ bin/containerd-shim-runc-v2
echo "CONTAINERD_VERSION: '1.6.0-rc.3'" | tee /root/go/src/github.com/containerd/containerd/_output/cri/opt/containerd/cluster/version
CONTAINERD_VERSION: '1.6.0-rc.3'
```
This looks good, so suggests that maybe the issue is with this branch, unless anyone can spot something I've done wrong?

**Comment by stevenhorsman** [comment]
Ignoring the version issue I've attempted the re-vendoring. It's been a while since I did it, so hopefully I've got the process correct:
- In kata-containers/src/runtime, I ran `go get github.com/containerd/containerd@v1.6.0-beta.4`
- To stop the vendor process complaining, I had to remove `github.com/containerd/containerd/api v1.6.0-beta.1` from `go.mod` . I'm not completely sure why, or if there is a better way
- Update the go mod replace with: `go mod edit -replace github.com/containerd/containerd=github.com/wllenyj/containerd@CCv0-rebase`
- Run: `make handle_vendor`

`go.mod` then references the slightly strange version:
```
replace (
	github.com/containerd/containerd => github.com/wllenyj/containerd v1.2.0-beta.2.0.20220209074753-e5287e3a54ad
...
```

I'll check this into my [test PR](https://github.com/kata-containers/kata-containers/pull/3640) and see what happens in the CI test

**Comment by stevenhorsman** [comment]
The builds are failing with incompatible changes e.g.:
```
# github.com/kata-containers/kata-containers/src/runtime/pkg/containerd-shim-v2
../../pkg/containerd-shim-v2/image.go:42:11: task.Local undefined (type *shim.TaskService has no field or method Local)
make: *** [Makefile:553: /home/runner/work/kata-containers/kata-containers/src/runtime/kata-runtime] Error 2
```
This is because some of the containerd APIs have changed since the `ali-CCv0` version. e.g. in its `shim.go`
```
type taskService struct {
	local shimapi.TaskService
}
```
whereas the new version has:
```
type taskService struct {
	shimapi.TaskService
}
```

@sameo - I think the only way to test this properly is to have a kata-container PR with the version update and re-vendoring as I've done *and* the kata-container changes to make it compatible, then run the tests against it. If they pass then we merge this PR update the version and vendoring to the confidential-containers fork and then re-run the test and merge them all together. Does that make sense to you?

@wllenyj - are you able to make the updates to kata-containers based on [my test branch](https://github.com/stevenhorsman/kata-containers/tree/CCv0-containerd-rebase) (I've invited you to collaborate on my kata fork repo) to make it work with the new containerd code and we can re-test https://github.com/kata-containers/kata-containers/pull/3640/files after those changes are pushed.

I hope this plan makes sense!

**Comment by sameo** [comment]
> The builds are failing with incompatible changes e.g.:
> 
> ```
> # github.com/kata-containers/kata-containers/src/runtime/pkg/containerd-shim-v2
> ../../pkg/containerd-shim-v2/image.go:42:11: task.Local undefined (type *shim.TaskService has no field or method Local)
> make: *** [Makefile:553: /home/runner/work/kata-containers/kata-containers/src/runtime/kata-runtime] Error 2
> ```
> 
> This is because some of the containerd APIs have changed since the `ali-CCv0` version. e.g. in its `shim.go`
> 
> ```
> type taskService struct {
> 	local shimapi.TaskService
> }
> ```
> 
> whereas the new version has:
> 
> ```
> type taskService struct {
> 	shimapi.TaskService
> }
> ```
> 
> @sameo - I think the only way to test this properly is to have a kata-container PR with the version update and re-vendoring as I've done _and_ the kata-container changes to make it compatible, then run the tests against it. If they pass then we merge this PR update the version and vendoring to the confidential-containers fork and then re-run the test and merge them all together. Does that make sense to you?
> 

It does, yes.

This is a burden though, we really need to think about a more scalable and less @stevenhorsman's time consuming way to maintain that branch.

**Comment by wllenyj** [comment]
@stevenhorsman Ok, I will try it.

**Comment by stevenhorsman** [comment]
> @stevenhorsman Ok, I will try it.

@wllenyj - I had a try myself and it might just be the error that I posted. I've added a fix for that in and am re-running the tests now: https://github.com/kata-containers/kata-containers/pull/3640

Obviously you know the code better than me, so please double check if there are any other issues. Thanks :)

**Comment by stevenhorsman** [comment]
From the [integration test](http://jenkins.katacontainers.io/job/kata-containers-CCv0-fedora-PR/151/console) it looks like there might be issues with containerd:
```
Events:
#   Type     Reason                  Age                From               Message
#   ----     ------                  ----               ----               -------
#   Normal   Scheduled               90s                default-scheduler  Successfully assigned default/handlers to fedoradocker32-5769c0
#   Warning  FailedCreatePodSandBox  12s (x6 over 87s)  kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = CreateContainer failed: ttrpc: closed: unknown
```
There also seems to be a failure in the static checks:
```
[static-checks.sh:366] INFO: Running golangci-lint on /home/runner/work/kata-containers/kata-containers/src/github.com/kata-containers/kata-containers/src/runtime/cmd/kata-runtime
Error: factory.go:238:98: SA1019: grpc.WithInsecure is deprecated: use insecure.NewCredentials() instead. Will be supported throughout 1.x. (staticcheck)
			conn, err := grpc.Dial(fmt.Sprintf("unix://%s", runtimeConfig.FactoryConfig.VMCacheEndpoint), grpc.WithInsecure())
			                                                                                              ^
```
but I'm not sure that code has changed, so it might be a re-vendor update that has caused it? I'll try and push a fix to that in the test PR

**Comment by stevenhorsman** [comment]
I've got the static checks all passing now, but the build and installed version of containerd (from the source branch of this PR) is not working in the integration tests. I've tried it locally as well and hitting similar problems:
```
$ sudo ctr run --runtime io.containerd.kata.v2 --rm -t quay.io/kata-containers/confidential-containers:signed test-kata uname -a
ctr: failed to create shim task: ttrpc: closed: unknown
```
The logs don't seem to be helpful either:
```
 journalctl -u containerd
-- Logs begin at Thu 2022-02-10 08:40:37 PST, end at Thu 2022-02-10 08:51:34 PST. --
-- No entries --
```
so I'm not sure of the next steps to debug. @wllenyj - did you have any luck getting it working?

**Comment by wllenyj** [comment]
@stevenhorsman I tested it in my own environment with no problems, I will build your environment and test it again.

And the ci of upstream containerd  is green: https://github.com/containerd/containerd/pull/5728, If there is any problem here, we focus directly on cc-related patches.

Try using kata without the vendor ? golang's vendor is really error-prone.

**Comment by wllenyj** [comment]
@stevenhorsman I create a new tag: v1.6.0-rc.4.0 at https://github.com/wllenyj/containerd/releases/tag/v1.6.0-rc.4.0, you can try it ? The version of golang seems to be recorded with git tag.

**Comment by stevenhorsman** [comment]
> @stevenhorsman I create a new tag: v1.6.0-rc.4.0 at https://github.com/wllenyj/containerd/releases/tag/v1.6.0-rc.4.0, you can try it ? The version of golang seems to be recorded with git tag.

I'll try running the ci, but the versioning is still not working properly. I think the issue is that your new tag is not verified, so is ignored by `git describe`:
image
```
# git describe
v1.2.0-beta.2-6325-ge5287e3a5
```
One thing I noticed that *might* be a cause of this is that you are forked from https://github.com/mxpv/containerd, rather than the main containerd repo. Is there a reason for this? My personal fork is up to date with the containerd main as I see:
```
$ git describe
v1.6.0-rc.4-4-ga7f43c892
```

**Comment by stevenhorsman** [comment]
> Try using kata without the vendor ? golang's vendor is really error-prone.

I'm not sure if I fully understand what you mean, but I've tried just updating the installed version of containerd to your branch and not updated any of the code to see if that helps in PR https://github.com/kata-containers/kata-containers/pull/3645

**Comment by stevenhorsman** [comment]
> Try using kata without the vendor ? golang's vendor is really error-prone.

It looks like that was a good hunch. The tests with just the version.yaml passed, so that means that issues is either with:
- the re-vendoring
- my compatibility changes being wrong, or not enough.

I'll try and have a play with the vendoring and see if I can cut done on the number of packages changes without causing errors.

Something like I noticed when looking at the branch: https://github.com/containerd/containerd/compare/main...wllenyj:CCv0-rebase?expand=1 is that there are still quite a lot of field and method renames to change the camel case style, which I'd personally like to see removed as they only make it more difficult to keep the branch up to date in future as you get merge conflicts in any changes in those areas.

**Comment by wllenyj** [comment]
> Something like I noticed when looking at the branch: https://github.com/containerd/containerd/compare/main...wllenyj:CCv0-rebase?expand=1 is that there are still quite a lot of field and method renames to change the camel case style, which I'd personally like to see removed as they only make it more difficult to keep the branch up to date in future as you get merge conflicts in any changes in those areas.

The `field and method renames` are used to methods reuse in cc logic, usually by capitalizing the first letter.

> the re-vendoring 

Can try to vendor to `upstream containerd`'s latest first and then vendor to CCv0-rebase. but CCv0-rebase without tag is a problem.  Can you try it with your personal fork ?
Or I push the CCv0-rebase to this repo ? And then tag `v1.6.0-rc.4.xxxxxx` ?

**Comment by stevenhorsman** [comment]
> Can try to vendor to `upstream containerd`'s latest first and then vendor to CCv0-rebase. but CCv0-rebase without tag is a problem.  Can you try it with your personal fork ?

That was the approach that I originally took, so I'm trying again just rebasing on your tag as maybe I got too much in with the containerd re-vendor. I'm testing it in https://github.com/kata-containers/kata-containers/pull/3647 now

**Comment by stevenhorsman** [comment]
> That was the approach that I originally took, so I'm trying again just rebasing on your tag as maybe I got too much in with the containerd re-vendor. I'm testing it in [kata-containers/kata-containers#3647](https://github.com/kata-containers/kata-containers/pull/3647) now

This test run failed in the same way in the integration tests and locally for me:
```
Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create containerd task: failed to create shim task: ttrpc: closed: unknown
```
@wllenyj - after the weekend do you think you can have a go at the re-vendoring and getting the kata runtime? I'm probably doing something obviously wrong, so you might have more luck getting it to work & debugging than me.

**Comment by wllenyj** [comment]
@stevenhorsman Ok, I'll do it in two days.

**Comment by wllenyj** [comment]
@stevenhorsman I made a re-vendor patch:https://github.com/kata-containers/kata-containers/pull/3653.
 let's see if ci can green, it can run start_container.sh for cc in my native.

**Comment by stevenhorsman** [comment]
All the integration tests in https://github.com/kata-containers/kata-containers/pull/3653 are now passing, so I think this is ready to be force pushed now. Thanks @wllenyj

**Review by stevenhorsman — APPROVED** [review]

**Comment by stevenhorsman** [comment]
I wonder if (once it is merged), we should rename the `ali-CCv0` branch as well now to something like `CC-main` as Samuel suggested. @sameo, do you think that after this merge would be a good time to do this rename?

**Review by sameo — APPROVED** [review]

**Comment by sameo** [comment]
> I wonder if (once it is merged), we should rename the `ali-CCv0` branch as well now to something like `CC-main` as Samuel suggested. @sameo, do you think that after this merge would be a good time to do this rename?

Yes, definitely. It's a good opportunity to have branch naming consistency.

**Comment by stevenhorsman** [comment]
@wllenyj - thanks for merging. I've updated the branch name and will work on getting this new code into the kata CCv0 branch :)

**Comment by wllenyj** [comment]
@stevenhorsman @sameo I have force push ali-CCv0, the original ali-CCv0 branch is backed up to https://github.com/wllenyj/containerd/tree/ali-CCv0.

**Comment by stevenhorsman** [comment]
@wllenyj - just something else I thought of. Do you think it is worth you pushing the version of containerd that you merged into this PR to `main` in our fork. Then if we want to see the differences between our fork and the main branch without them being out of sync we can just compare `confidential-containers/containerd:main` and `confidential-containers/containerd:CC-main`. AFAIK we aren't using `confidential-containers/containerd:main` for anything else?

**Comment by wllenyj** [comment]
`confidential-containers/containerd:main` is synchronized with upstream main of containerd ? Is it possible to directly compare containerd:main and cc/containerd:main ?

**Comment by stevenhorsman** [comment]
> `confidential-containers/containerd:main` is synchronized with upstream main of containerd ?

Sorry if I wasn't clear. I'm seeing that our https://github.com/confidential-containers/containerd main branch hasn't been updated since October, so it old:
image

What I was suggesting is that you push the version of upstream containerd you rebased the `ali-CCv0` updates on, to `confidential-containers/containerd:main`

Then in future we can see all of the CC specific commits easily by viewing: https://github.com/confidential-containers/containerd/compare/main...confidential-containers:CC-main?expand=1
(if you see now there are 438 commits different, but I think only 15 of them are yours and related to the confidential containers plugin changes). Does that make any more sense?

**Comment by wllenyj** [comment]
@stevenhorsman Ok, you are right.

**Comment by wllenyj** [comment]
@stevenhorsman I have rebase cc:main to upstream:a9f61ba, and this commit `a9f61ba` is the basis of CC-main.

**Comment by stevenhorsman** [comment]
> @stevenhorsman I have rebase cc:main to upstream:a9f61ba, and this commit `a9f61ba` is the basis of CC-main.

Awesome. Thanks so much. A few people have asked me in the past what specific changes we've had to make to containerd for CC and now it will be easy to show them :)

**Pull request merged**
