### PR TITLE
rebase to upstream 1.6.1

### PR DESCRIPTION
**Pull request by wllenyj**
To support https://github.com/kata-containers/kata-containers/pull/3822

### CODE REVIEW

**Comment by wllenyj** [comment]
@sameo @fidencio @stevenhorsman  Some comments? 
We first need to test it in CC-test.

Thanks.

**Comment by fidencio** [comment]
Yep, please, hold it till I am able to do the bump also on the Kata Containers side.

**Comment by stevenhorsman** [comment]
@wllenyj, do you want me to prep the CCv0 PR that tests this rebase branch like last time? @fidencio - this shouldn't cause any problems as we won't merge it until we sync, but it will be good to get up-to-date with you.

**Comment by stevenhorsman** [comment]
FYI: I've created the issue https://github.com/kata-containers/kata-containers/issues/3830 to cover the kata-containers testing of this PR

**Comment by stevenhorsman** [comment]
I'm not sure if we should worry about the nightly windows test failure, but my [PR](https://github.com/kata-containers/kata-containers/pull/3832) testing the kata pipeline was successful and I did a small amount of CC manual testing that also worked, so I think we can merge this now?

**Review by stevenhorsman — APPROVED** [review]
Kata containers testing passed, so I think that's good enough. Thanks!

**Comment by wllenyj** [comment]
@stevenhorsman Thank you.
The `Nightly / Windows` test failed because one of the patches did not support windows. I felt that there should be no windows in kata, so I didn't consider windows at that time.

If no other comments, I will do the merge.

**Comment by stevenhorsman** [comment]
> @stevenhorsman Thank you. The `Nightly / Windows` test failed because one of the patches did not support windows. I felt that there should be no windows in kata, so I didn't consider windows at that time.
> 
> If no other comments, I will do the merge.

Awesome. Are you happy for us to merge this now?

**Pull request merged**
