### PR TITLE
Rebase to upstream v1.6.6

### PR DESCRIPTION
**Pull request by wllenyj**
This pr is rebased on https://github.com/containerd/containerd/releases/tag/v1.6.6.

See https://github.com/confidential-containers/containerd/compare/v1.6.6...wllenyj:rebase-1.6.6 for all changes.

If the CC-test passes, we need to force push CC-main.

cc @stevenhorsman.

### CODE REVIEW

**Comment by stevenhorsman** [comment]
We've had some problems with the kata-containers integration test, where it looks like the newer version of `crictl` is not working properly? Details in the [kata-containers PR](https://github.com/kata-containers/kata-containers/pull/4490)

**Comment by stevenhorsman** [comment]
In https://github.com/kata-containers/kata-containers/pull/4490 (after some fun with crictl) we've been able to get this code working with CCv0 and the CI tests running and it working manually too, so I'm happy with the code changes.
image

**Review by stevenhorsman — APPROVED** [review]
After fixing up the crictl version jump problems we've got this code working, so I'm happy for it to be force pushed. @wllenyj - thanks for you work and patience with our troubles testing it.

**Comment by wllenyj** [comment]
@stevenhorsman Thanks for your test.
I will do a forced push.

**Comment by wllenyj** [comment]
> I will do a forced push.

Done

See https://github.com/confidential-containers/containerd/compare/v1.6.6...confidential-containers:CC-main  for all changes.
And the previous CC-main is backed up to the [CC-main-backup](https://github.com/confidential-containers/containerd/tree/CC-main-backup) branch.

cc @stevenhorsman

**Comment by stevenhorsman** [comment]
> > I will do a forced push.
> 
> Done
> 
> See [v1.6.6...confidential-containers:CC-main](https://github.com/confidential-containers/containerd/compare/v1.6.6...confidential-containers:CC-main) for all changes. And the previous CC-main is backed up to the [CC-main-backup](https://github.com/confidential-containers/containerd/tree/CC-main-backup) branch.
> 
> cc @stevenhorsman

Thanks very much, we'll switch the PR back to use the updated `CC-main` branch and get it tested and merged in.

**Pull request merged**
